snap install code --classic
code --install-extension alefragnani.project-manager
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension GitLab.gitlab-workflow
code --install-extension mongodb.mongodb-vscode
code --install-extension ms-azuretools.vscode-docker
code --install.extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cpptools
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mssql
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension mtxr.sqltools-driver-pg
code --install-extension mtxr.sqltools-driver-sqlite
code --install-extension jordanhury.sqltools-cassandra
code --install-extension saposs.sap-hana-driver-for-sqltools
code --install-extension koszti.snowflake-driver-for-sqltools
code --install-extension ultram4rine.sqltools-clickhouse-driver
code --install-extension kj.sqltools-driver-redshift
code --install-extension google-cloud-spanner-ecosystem.google-cloud-spanner-driver
code --install-extension brunoventura.sqltools-athena-driver
code --install-extension PKief.material-icon-theme
code --install-extension platformio.platformio-ide
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vscodevim.vim
code --install-extension Wscats.eno
code --install-extension zhuangtongfa.material-theme
code --install-extension ziyasal.vscode-open-in-github
code --install-extension formulahendry.code-runner
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension 2gua.rainbow-brackets
code --install-extension 4tron.stack-overflow-view
code --install-extension techer.open-in-browser
code --install-extension cweijan.vscode-ssh
code --install-extension mkloubert.vscode-kanban
code --install-extension ritwickdey.liveserver
code --install-extension github.vscode-pull-request-github
code --install-extension usernamehw.errorlens
code --install-extension rohinivsenthil.postcode
#this one is just for fun, delete if you want :)
code --install-extension bar9.stories
code --install-extension benawad.vsinder
code --install-extension mkloubert.vs-media-player
code --install-extension ajshort.latex-preview
